Repository web-infra-dev/rsdoctor, pull requests merged in 2024-06, with the labels that each got.

#362 feat(sdk): socket protocol problem
  .changeset/flat-dogs-ring.md
  packages/components/src/utils/data/local.ts
  packages/components/src/utils/socket.ts
Labels: change: feat

#373 fix(plugin): report code type error on rspack builder
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/graph/src/graph/module-graph/module.ts
Labels: change: fix

#371 feat: support port
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/document/docs/en/config/options/options.mdx
  packages/document/docs/zh/config/options/options.mdx
  packages/rspack-plugin/src/plugin.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: feat

#372 feat(plugin): add no parse bundle options
  packages/core/src/build-utils/build/chunks/assetsModules.ts
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
Labels: change: feat

#377 docs: fix discord badge
  README.md
  README.zh-CN.md
Labels: change: docs

#378 docs: add 404 page and netlify redirect
  packages/document/docs/404.mdx
  packages/document/docs/public/netlify.toml
Labels: change: docs

#386 fix(graph): this module which don't in any chunk no need to be counted
  packages/graph/src/graph/package-graph/graph.ts
Labels: change: fix

#393 feat(plugin): support for esm loader which its ext is .js in rspack
  e2e/cases/doctor-rspack/fixtures/loaders/esm/esm-serialize-query-to-comment.js
  e2e/cases/doctor-rspack/fixtures/loaders/esm/package.json
  e2e/cases/doctor-rspack/plugin.test.ts
  packages/core/src/build-utils/build/utils/loader.ts
  packages/core/src/inner-plugins/utils/loader.ts
  packages/core/tests/build/utils/loader/changeBuiltinLoader.test.ts
  packages/graph/package.json
  packages/graph/src/graph/package-graph/graph.ts
  packages/graph/src/graph/package-graph/utils.ts
  packages/graph/tests/__snapshots__/module-graph.spec.ts.snap
  packages/graph/tests/__snapshots__/utils.spec.ts.snap
  packages/graph/tests/fixture/index/index.js
  packages/graph/tests/fixture/index/package.json
  packages/graph/tests/fixture/package.json
  packages/graph/tests/utils.spec.ts
  packages/rspack-plugin/src/probeLoaderPlugin.ts
  packages/types/src/sdk/package.ts
  packages/utils/src/build/json.ts
  pnpm-lock.yaml
Labels: change: feat
