Repository web-infra-dev/rsdoctor, pull requests merged in 2024-04, with the labels that each got.

#283 docs: update contributing guide
  CONTRIBUTING.md
Labels: change: docs

#294 fix(client): fix layout style ui
  packages/components/src/components/Layout/menus.tsx
Labels: change: fix

#296 docs: fix next.js code example
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/document/docs/en/guide/start/quick-start-shared.mdx
  packages/document/docs/zh/guide/start/quick-start-shared.mdx
Labels: change: docs

#297 fix: make ECMA check log more authentic
  packages/core/src/rules/rules/ecma-version-check/index.ts
Labels: change: fix

#298 feat(plugin): add the analysis of tree-shaking feature
  .changeset/dirty-seahorses-lick.md
  .changeset/healthy-dolphins-lick.md
  e2e/cases/doctor-webpack/plugins/treeShaking.test.ts
  examples/modern-minimal/modern.config.ts
  packages/client/src/router.tsx
  packages/components/package.json
  packages/components/src/components/Layout/menus.tsx
  packages/components/src/pages/TreeShaking/constants.ts
  packages/components/src/pages/TreeShaking/editor.tsx
  packages/components/src/pages/TreeShaking/index.scss
  packages/components/src/pages/TreeShaking/index.tsx
  packages/components/src/pages/TreeShaking/open-tag.ts
  packages/components/src/pages/TreeShaking/space.tsx
  packages/components/src/pages/TreeShaking/table.tsx
  packages/components/src/pages/TreeShaking/types.ts
  packages/components/src/pages/TreeShaking/utils.tsx
  packages/components/src/pages/index.ts
  packages/components/src/utils/url.ts
  packages/core/src/build-utils/build/module-graph/treeShaking.ts
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
  pnpm-lock.yaml
Labels: change: feat

#300 fix(plugin): the error of analyzing the missing builtin loader when rspack uses dev mode
  packages/rspack-plugin/src/builtinLoaderPlugin.ts
Labels: change: fix

#305 fix(core): the types exports problem
  packages/core/package.json
Labels: change: fix

#313 fix: @rsdoctor/core types exports
  packages/core/package.json
  packages/utils/package.json
Labels: change: fix

#315 fix: multi plugin rspack output path error
  packages/rspack-plugin/src/plugin.ts
Labels: change: fix

#320 fix: rspack multi plugin output error
  .changeset/lemon-geckos-shop.md
  packages/rspack-plugin/src/plugin.ts
Labels: change: fix

#321 fix(type): the rule's config types to support for user to set the rule config:
  packages/core/src/inner-plugins/plugins/base.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/src/plugin.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: fix

#324 fix(plugin): add error-plugin
  packages/rspack-plugin/src/plugin.ts
Labels: change: fix
