Repository web-infra-dev/rsdoctor, pull requests merged in 2024-09, with the labels that each got.

#498 fix(sdk): saveManifest need await when brief mode
  .changeset/stupid-comics-mate.md
  packages/sdk/src/sdk/sdk/webpack.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: fix

#504 fix: some @types/webpack types error
  e2e/cases/doctor-webpack/plugins/plugin.test.ts
  e2e/package.json
  examples/multiple-minimal/package.json
  examples/webpack-minimal/package.json
  packages/client/package.json
  packages/core/package.json
  packages/core/src/inner-plugins/plugins/bundle.ts
  packages/types/package.json
  packages/types/src/sdk/server/apis/index.ts
  packages/webpack-plugin/package.json
  packages/webpack-plugin/src/plugins/resolver.ts
  pnpm-lock.yaml
  scripts/test-helper/package.json
  scripts/test-helper/src/webpack.ts
Labels: change: fix

#512 perf(deps): remove `webpack-sources` to reduce dependencies
  packages/core/package.json
  packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
  packages/types/src/plugin/baseCompiler.ts
  pnpm-lock.yaml
Labels: change: perf

#513 feat: add sort package-relation by desc
  packages/components/src/components/Alerts/common.tsx
Labels: change: feat

#517 docs(fix): should use ssr for document
  packages/document/docs/404.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#519 feat(cli): support bundle diff cli
  .gitignore
  e2e/cases/doctor-rspack/bundle-diff.test.ts
  e2e/fixtures/.rsdoctor/chunkGraph/0
  e2e/fixtures/.rsdoctor/configs/0
  e2e/fixtures/.rsdoctor/envinfo/0
  e2e/fixtures/.rsdoctor/errors/0
  e2e/fixtures/.rsdoctor/loader/0
  e2e/fixtures/.rsdoctor/manifest.json
  e2e/fixtures/.rsdoctor/moduleCodeMap/0
  e2e/fixtures/.rsdoctor/moduleGraph/0
  e2e/fixtures/.rsdoctor/otherReports/0
  e2e/fixtures/.rsdoctor/packageGraph/0
  e2e/fixtures/.rsdoctor/plugin/0
  e2e/fixtures/.rsdoctor/resolver/0
  e2e/fixtures/.rsdoctor/summary/0
  e2e/fixtures/manifests/empty-manifest.json
  e2e/package.json
  e2e/test-kit/index.ts
  e2e/test-kit/launch.ts
  e2e/test-kit/path.ts
  examples/rspack-banner-minimal/rspack.config.js
  packages/cli/src/commands/bundle-diff.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/constants.ts
  packages/cli/src/index.ts
  packages/client/src/router.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/assets.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/cards.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/changes.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/constants.ts
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/index.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/modules.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/overview.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/packages.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/row.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/types.ts
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/utils.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffServerAPIProvider/index.tsx
  packages/components/src/pages/Resources/BundleDiff/constants.tsx
  packages/components/src/pages/Resources/BundleDiff/index.tsx
  packages/components/src/pages/index.ts
  packages/sdk/src/sdk/server/index.ts
  packages/sdk/src/sdk/utils/openBrowser.ts
  pnpm-lock.yaml
  vitest.workspace.ts
Labels: change: feat

#520 fix(core): banner plugin switch error
  .gitignore
  examples/rspack-banner-minimal/rspack.config.js
  packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
  packages/core/src/inner-plugins/utils/config.ts
Labels: change: fix

#528 fix: gitignore e2e fixtuers/rsdoctor
  .gitignore
  e2e/cases/doctor-rspack/bundle-diff.test.ts
  e2e/fixtures/.rsdoctor/manifest.json
  e2e/fixtures/rsdoctor/chunkGraph/0
  e2e/fixtures/rsdoctor/configs/0
  e2e/fixtures/rsdoctor/envinfo/0
  e2e/fixtures/rsdoctor/errors/0
  e2e/fixtures/rsdoctor/loader/0
  e2e/fixtures/rsdoctor/manifest.json
  e2e/fixtures/rsdoctor/moduleCodeMap/0
  e2e/fixtures/rsdoctor/moduleGraph/0
  e2e/fixtures/rsdoctor/otherReports/0
  e2e/fixtures/rsdoctor/packageGraph/0
  e2e/fixtures/rsdoctor/plugin/0
  e2e/fixtures/rsdoctor/resolver/0
  e2e/fixtures/rsdoctor/summary/0
  e2e/test-kit/path.ts
Labels: change: fix

#529 fix(diff): correct socket address for local server when running diff CLI
  packages/components/src/utils/data/local.ts
  packages/components/src/utils/socket.ts
Labels: change: fix

#530 feat(loader): support rspack's builtin:lightningcss-loader
  e2e/cases/doctor-rspack/fixtures/index.css
  e2e/cases/doctor-rspack/plugin.test.ts
  examples/rspack-minimal/package.json
  examples/rspack-minimal/rspack.config.js
  packages/core/src/build-utils/build/loader/probeLoaderPlugin.ts
  pnpm-lock.yaml
Labels: change: feat

#535 feat: add new context field to support embedded rsdoctor to other page
  packages/components/src/components/Layout/index.tsx
  packages/components/src/config.tsx
Labels: change: feat
