Repository web-infra-dev/rsdoctor, pull requests merged in 2024-12, with the labels that each got.

#608 fix(multi-plugin): fix multi-plugin options error
  .changeset/strong-games-beam.md
  e2e/cases/doctor-webpack/plugins/multi-plugin-brief.test.ts
  e2e/cases/doctor-webpack/test-utils.ts
  e2e/playwright.config.ts
  packages/rspack-plugin/src/multiple.ts
  packages/sdk/src/sdk/multiple/controller.ts
  packages/sdk/src/sdk/multiple/slave.ts
  packages/sdk/src/sdk/sdk/index.ts
  packages/webpack-plugin/src/multiple.ts
Labels: change: fix

#610 fix: circular configs options data
  .changeset/eleven-ligers-attack.md
  packages/sdk/package.json
  packages/sdk/src/sdk/sdk/core.ts
  packages/sdk/src/sdk/sdk/index.ts
  packages/utils/src/common/algorithm.ts
  pnpm-lock.yaml
Labels: change: fix

#624 fix: typo error
  packages/components/src/components/Alert/index.tsx
  packages/components/src/components/Alert/types.ts
  packages/sdk/src/sdk/multiple/controller.ts
  packages/sdk/src/sdk/multiple/index.ts
  packages/sdk/src/sdk/multiple/primary.ts
  packages/sdk/src/sdk/multiple/server.ts
  packages/types/src/rule/data.ts
Labels: change: fix

#635 feat: multiple plugim with envrioments
  packages/rspack-plugin/src/multiple.ts
  packages/sdk/src/sdk/multiple/primary.ts
  packages/webpack-plugin/src/multiple.ts
Labels: change: feat

#641 fix: tile graph with reportDir
  packages/core/src/build-utils/build/chunks/generateTileGraph.ts
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
Labels: change: fix

#644 perf: reduce the bundle size of client
  packages/client/rsbuild.config.ts
  packages/components/src/pages/TreeShaking/table.tsx
  packages/components/src/pages/TreeShaking/utils.tsx
  packages/graph/package.json
  packages/graph/src/graph/module-graph/module.ts
  packages/graph/src/graph/module-graph/utils.ts
  packages/graph/src/graph/package-graph/graph.ts
  packages/utils/package.json
  packages/utils/src/common/index.ts
  packages/utils/src/common/lodash.ts
  packages/utils/src/common/package.ts
  packages/utils/src/error/error.ts
  packages/utils/src/rule-utils/document/document.ts
  packages/utils/src/rule-utils/parser/asserts.ts
  pnpm-lock.yaml
Labels: change: perf

#649 fix(client): the problem of the client's HMR
  packages/components/src/utils/request.ts
Labels: change: fix

#654 feat(client): timeline components ui
  packages/client/src/App.tsx
  packages/components/src/components/Alerts/overlay.tsx
  packages/components/src/components/Charts/TimelineCharts/index.tsx
  packages/components/src/components/Charts/bootstrap.tsx
  packages/components/src/components/Charts/common.tsx
  packages/components/src/components/Charts/constants.ts
  packages/components/src/components/Charts/done.tsx
  packages/components/src/components/Charts/index.tsx
  packages/components/src/components/Charts/loader.tsx
  packages/components/src/components/Charts/minify.tsx
  packages/components/src/components/Select/index.tsx
  packages/components/src/constants.tsx
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/components/src/pages/BundleSize/components/index.tsx
  packages/components/src/pages/ModuleAnalyze/fileTree.tsx
  packages/components/src/pages/WebpackLoaders/Overall/index.tsx
  packages/components/src/utils/data/brief.ts
  pnpm-lock.yaml
Labels: change: feat

#655 feat: support syntax check
  e2e/cases/doctor-rspack/plugin.test.ts
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/client/rsbuild.config.ts
  packages/components/package.json
  packages/components/src/components/Alert/ecma-version-check.module.scss
  packages/components/src/components/Alert/ecma-version-check.tsx
  packages/components/src/components/Alert/types.ts
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/core/package.json
  packages/core/src/rules/rules/ecma-version-check/index.ts
  packages/core/src/rules/rules/ecma-version-check/types.ts
  packages/document/docs/en/guide/usage/rule-config.mdx
  packages/document/docs/zh/guide/usage/rule-config.mdx
  packages/rspack-plugin/src/plugin.ts
  pnpm-lock.yaml
  scripts/test-helper/src/rspack.ts
Labels: change: feat

#658 docs: fix grammar
  packages/document/docs/en/guide/start/intro.mdx
Labels: change: docs

#657 feat(ui): optimize the Layout component
  packages/components/src/components/Layout/bundle-size-icon.svg
  packages/components/src/components/Layout/compile-icon.svg
  packages/components/src/components/Layout/menus.tsx
  packages/components/src/components/Layout/overall-icon.svg
Labels: change: feat

#664 feat: add new version of bundle size bar
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/components/src/components/Card/size.module.scss
  packages/components/src/components/Card/size.tsx
  packages/components/src/components/Card/statistic.tsx
  packages/components/src/components/Overall/bundle.tsx
  packages/components/src/pages/BundleSize/components/card.module.scss
  packages/components/src/pages/BundleSize/components/cards.tsx
  pnpm-lock.yaml
Labels: change: feat

#665 fix(UI): failed to render `font-family-code` in macOS
  packages/components/src/pages/Overall/index.module.scss
Labels: change: fix

#666 fix(UI): correct versions and title alignment
  packages/components/src/components/Alerts/collapse.tsx
  packages/components/src/components/Overall/help-center.module.scss
Labels: change: fix
