Repository web-infra-dev/rsdoctor, pull requests merged in 2024-11, with the labels that each got.

#573 fix(plugin): multi webpack plugin setSDK error
  packages/webpack-plugin/src/plugin.ts
Labels: change: fix

#574 feat: Automatically switch language when first visit
  packages/components/src/components/Layout/index.tsx
  packages/components/src/utils/locale.ts
  packages/components/src/utils/storage.tsx
Labels: change: feat

#583 feat: support the layer data
  packages/core/src/build-utils/common/module-graph/transform.ts
  packages/graph/src/graph/module-graph/graph.ts
  packages/graph/src/graph/module-graph/module.ts
  packages/sdk/src/sdk/sdk/index.ts
  packages/sdk/src/sdk/sdk/webpack.ts
  packages/types/src/plugin/baseStats.ts
  packages/types/src/sdk/module.ts
Labels: change: feat

#590 fix: should link to English documentation
  packages/components/src/pages/BundleSize/components/index.tsx
Labels: change: fix

#592 perf(client): remove client-side terser minification
  packages/components/package.json
  packages/components/src/components/Layout/header.tsx
  packages/components/src/components/Loader/executions.tsx
  packages/components/src/components/worker/jsequal/client.tsx
  packages/components/src/components/worker/jsequal/worker.js
  pnpm-lock.yaml
Labels: change: perf

#589 feat: support rspack layers
  e2e/cases/doctor-rspack/layer-plugin.test.ts
  e2e/test-results/.last-run.json
  examples/rspack-layers-minimal/build.ts
  examples/rspack-layers-minimal/index.html
  examples/rspack-layers-minimal/legacy-loader.js
  examples/rspack-layers-minimal/package.json
  examples/rspack-layers-minimal/public/favicon.ico
  examples/rspack-layers-minimal/public/logo192.png
  examples/rspack-layers-minimal/public/logo512.png
  examples/rspack-layers-minimal/public/manifest.json
  examples/rspack-layers-minimal/public/robots.txt
  examples/rspack-layers-minimal/rspack.config.js
  examples/rspack-layers-minimal/src/App.css
  examples/rspack-layers-minimal/src/App.tsx
  examples/rspack-layers-minimal/src/Footer/index.tsx
  examples/rspack-layers-minimal/src/Footer/style/index.module.less
  examples/rspack-layers-minimal/src/app1.tsx
  examples/rspack-layers-minimal/src/declaration.d.ts
  examples/rspack-layers-minimal/src/index.css
  examples/rspack-layers-minimal/src/index.module.less
  examples/rspack-layers-minimal/src/index.ts
  examples/rspack-layers-minimal/src/index.tsx
  examples/rspack-layers-minimal/src/logo.svg
  examples/rspack-layers-minimal/src/react-app-env.d.ts
  examples/rspack-layers-minimal/src/reportWebVitals.ts
  examples/rspack-layers-minimal/src/setupTests.ts
  examples/rspack-layers-minimal/src/typings/assetsDefinition.d.ts
  examples/rspack-layers-minimal/tsconfig.json
  packages/components/src/components/Charts/index.tsx
  packages/components/src/components/Charts/utils.ts
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/Analysis/index.tsx
  packages/components/src/components/Select/index.tsx
  packages/components/src/pages/WebpackLoaders/Analysis/index.tsx
  packages/components/src/utils/loader.ts
  packages/core/src/build-utils/build/loader/probeLoader.ts
  packages/core/src/inner-plugins/utils/loader.ts
  packages/graph/src/graph/module-graph/graph.ts
  packages/graph/src/graph/module-graph/module.ts
  packages/types/src/plugin/baseLoader.ts
  packages/types/src/sdk/loader.ts
  packages/types/src/sdk/module.ts
  packages/types/src/sdk/server/apis/index.ts
  packages/types/src/sdk/server/apis/loader.ts
  packages/utils/src/common/data/index.ts
  packages/utils/src/common/loader.ts
  pnpm-lock.yaml
  scripts/test-helper/src/rspack.ts
Labels: change: feat

#596 fix(client): eliminate Sass deprecation warning
  packages/client/src/common/styles/base.scss
Labels: change: fix

#603 fix(rspack-plugin): rspack moduleGrpah js api don't have getResolvedModule
  packages/core/src/build-utils/common/webpack/compatible.ts
Labels: change: fix

#606 fix: file Extension util
  packages/utils/src/common/graph/assets.ts
Labels: change: fix
