Repository web-infra-dev/rsdoctor, pull requests merged in 2024-05, with the labels that each got.

#327 fix(plugin): the BuiltinLoaderPlugin should skipped when close 'loader' in features
  .changeset/popular-hotels-bow.md
  packages/rspack-plugin/src/plugin.ts
Labels: change: fix

#328 fix(core): change core package‘s @rsdoctor/types from dev to dependencien.
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#336 docs: bump rspress and rsfamily-nav-icon
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: docs

#337 fix: remove use of rspack compiler.compilation api
  packages/rspack-plugin/src/plugin.ts
Labels: change: fix

#334 feat(core): modify severity of rules dynamically at runtime
  .changeset/cold-dryers-live.md
  packages/core/src/rules/rule.ts
  packages/types/src/linter/diagnostic.ts
Labels: change: feat

#342 fix(config): fix some config problem
  packages/client/rsbuild.config.ts
  packages/client/tsconfig.json
  packages/components/tsconfig.json
  scripts/tsconfig/base.json
Labels: change: fix

#343 fix(cli): support for online data fetch
  packages/cli/src/commands/analyze.ts
Labels: change: fix

#349 docs(CONTRIBUTING.md): fix error description (e2e command)
  CONTRIBUTING.md
Labels: change: docs

#353 fix(plugin): dpendcies problem
  e2e/cases/doctor-rspack/banner-plugin.test.ts
  packages/rspack-plugin/package.json
  packages/rspack-plugin/src/plugin.ts
  packages/webpack-plugin/package.json
  pnpm-lock.yaml
Labels: change: fix

#355 feat(plugin): open the banner plugin
  e2e/cases/doctor-rspack/banner-plugin.test.ts
  packages/rspack-plugin/src/plugin.ts
Labels: change: feat

#357 feat: support for banner plugin.
  packages/core/package.json
  packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
  packages/core/src/inner-plugins/plugins/index.ts
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/package.json
  packages/rspack-plugin/src/plugin.ts
  packages/webpack-plugin/src/plugin.ts
  pnpm-lock.yaml
Labels: change: feat
