Repository web-infra-dev/rsdoctor, pull requests merged in 2024-08, with the labels that each got.

#451 feat(plugin): add pringLog options to control the terminal log outputs
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/src/plugin.ts
  packages/sdk/src/sdk/sdk/types.ts
  packages/sdk/src/sdk/sdk/webpack.ts
  packages/sdk/src/sdk/server/index.ts
  packages/types/src/sdk/instance.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: feat

#457 docs: add Rslib links
  README.md
  README.zh-CN.md
  scripts/dictionary.txt
Labels: change: docs

#458 docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
  packages/document/package.json
  packages/document/theme/components/ToolStack.tsx
  packages/document/theme/index.tsx
  pnpm-lock.yaml
Labels: change: docs

#452 fix(loader): proxy loader no module error
  packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
  packages/core/src/inner-plugins/plugins/loader.ts
Labels: change: fix

#475 feat: add mode options & brief mode
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/client/rsbuild.config.ts
  packages/client/src/router.tsx
  packages/components/src/components/Alert/package-relation.tsx
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/Analysis/index.tsx
  packages/components/src/pages/TreeShaking/index.tsx
  packages/components/src/pages/WebpackLoaders/Analysis/index.tsx
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/graph/src/graph/chunk-graph/asset.ts
  packages/graph/src/graph/module-graph/module.ts
  packages/rspack-plugin/src/plugin.ts
  packages/sdk/src/sdk/sdk/webpack.ts
  packages/types/src/sdk/instance.ts
  packages/types/src/sdk/module.ts
Labels: change: feat

#483 fix(progress): do not abort compilation when emit fails
  packages/core/src/inner-plugins/plugins/progress.ts
Labels: change: fix

#485 feature: add brief configs
  e2e/cases/doctor-rspack/brief.test.ts
  e2e/package.json
  e2e/playwright.config.ts
  packages/components/src/components/BundleDiff/DiffServerAPIProvider/index.tsx
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/src/plugin.ts
  packages/sdk/src/sdk/sdk/core.ts
  packages/sdk/src/sdk/sdk/webpack.ts
  packages/types/src/sdk/instance.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: feat

#487 docs: add SECURITY.md
  SECURITY.md
Labels: change: docs
