Repository web-infra-dev/rsdoctor, pull requests merged in 2024-07, with the labels that each got.

#406 feat: support to open/close the generating of tile graph
  examples/modern-minimal/package.json
  package.json
  packages/components/src/pages/BundleSize/components/index.tsx
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/src/plugin.ts
  pnpm-lock.yaml
Labels: change: feat

#411 docs: remove underlines between badges
  README.md
  README.zh-CN.md
Labels: change: docs

#412 perf: optimize the package graph algorithm
  packages/graph/src/graph/package-graph/package.ts
Labels: change: perf

#421 fix(server): the client page get error on '/' path
  packages/sdk/src/sdk/server/apis/renderer.ts
  packages/sdk/src/sdk/server/index.ts
Labels: change: fix

#424 fix: json stringfy some useless code
  packages/utils/src/build/json.ts
Labels: change: fix

#430 docs: update homepage and theme
  packages/client/src/index.tsx
  packages/components/src/components/Layout/header.tsx
  packages/document/docs/en/guide/more/rules.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/guide/more/rules.mdx
  packages/document/docs/zh/index.md
  packages/document/i18n.json
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/document/tailwind.config.js
  packages/document/theme/components/HomeFeatures/index.module.scss
  packages/document/theme/components/HomeFeatures/index.tsx
  packages/document/theme/components/HomeFooter/index.tsx
  packages/document/theme/components/HomeHero/index.module.scss
  packages/document/theme/components/HomeHero/index.tsx
  packages/document/theme/components/NextSteps.module.scss
  packages/document/theme/components/NextSteps.tsx
  packages/document/theme/components/Overview.module.scss
  packages/document/theme/components/Overview.tsx
  packages/document/theme/components/RuleIndex.module.scss
  packages/document/theme/components/RuleIndex.tsx
  packages/document/theme/components/Step.module.scss
  packages/document/theme/components/Step.tsx
  packages/document/theme/components/ToolStack.module.scss
  packages/document/theme/components/ToolStack.tsx
  packages/document/theme/global.d.ts
  packages/document/theme/index.css
  packages/document/theme/index.tsx
  packages/document/theme/pages/index.tsx
  packages/document/theme/utils.ts
  packages/document/tsconfig.json
  pnpm-lock.yaml
Labels: change: docs

#433 fix(sdk): error on write Manifest.json
  .changeset/cuddly-radios-wink.md
  packages/sdk/src/sdk/sdk/core.ts
Labels: change: fix

#438 docs: fix wording of plugin used in rsbuild
  packages/document/docs/zh/guide/start/quick-start-shared.mdx
Labels: change: docs

#436 fix: change ip to resolve the ip's SSRF risk
  packages/sdk/package.json
  packages/sdk/src/sdk/server/apis/project.ts
  packages/sdk/src/sdk/server/index.ts
  packages/sdk/src/sdk/server/utils.ts
  packages/sdk/tests/server/apis/project.test.ts
  pnpm-lock.yaml
Labels: change: fix

#441 fix(client): module code show error
  packages/components/src/pages/BundleSize/components/asset.tsx
Labels: change: fix

#447 fix(sdk): HMR opens a new tab instead of updating the exsiting tab
  packages/sdk/src/sdk/utils/openBrowser.ts
Labels: change: fix
