Repository web-infra-dev/rsdoctor, pull requests merged in 2025-01, with the labels that each got.

#668 fix: dev:doc script
  package.json
Labels: change: fix

#659 feat(ui): optimize the loader analysis page
  packages/client/src/App.tsx
  packages/components/src/common/svg/files/css.svg
  packages/components/src/common/svg/files/html.svg
  packages/components/src/common/svg/files/image.svg
  packages/components/src/common/svg/files/js.svg
  packages/components/src/common/svg/files/unkown-file.svg
  packages/components/src/common/svg/loader/input.svg
  packages/components/src/common/svg/loader/output.svg
  packages/components/src/common/svg/loader/step.svg
  packages/components/src/common/svg/overall/bundle-size-icon.svg
  packages/components/src/common/svg/overall/compile-icon.svg
  packages/components/src/common/svg/overall/overall-icon.svg
  packages/components/src/components/Alerts/bundle.tsx
  packages/components/src/components/CodeViewer/diff.tsx
  packages/components/src/components/FileTree/index.scss
  packages/components/src/components/FileTree/index.tsx
  packages/components/src/components/Keyword/index.tsx
  packages/components/src/components/Keyword/style.module.scss
  packages/components/src/components/Layout/menus.tsx
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/Analysis/index.tsx
  packages/components/src/components/Loader/Analysis/style.module.scss
  packages/components/src/components/Loader/executions.tsx
  packages/components/src/pages/WebpackLoaders/Analysis/index.tsx
Labels: change: feat

#674 fix(ui): detail fixed
  packages/client/src/App.tsx
  packages/components/src/components/Alert/ecma-version-check.module.scss
  packages/components/src/components/Alerts/bundle-alert.module.scss
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/components/src/components/Alerts/collapse.module.scss
  packages/components/src/components/Alerts/collapse.tsx
  packages/components/src/components/Alerts/list.module.scss
  packages/components/src/components/Card/index.tsx
  packages/components/src/components/Card/size.module.scss
  packages/components/src/components/Card/size.tsx
  packages/components/src/components/Card/statistic.scss
  packages/components/src/components/Charts/bootstrap.tsx
  packages/components/src/components/Charts/done.tsx
  packages/components/src/components/Configuration/builder.module.scss
  packages/components/src/components/Configuration/builder.tsx
  packages/components/src/components/Overall/DataSummary.module.scss
  packages/components/src/components/Overall/bundle.module.scss
  packages/components/src/components/Overall/bundle.tsx
  packages/components/src/components/Overall/card.module.scss
  packages/components/src/components/Overall/compile.module.scss
  packages/components/src/components/Overall/compile.tsx
  packages/components/src/components/Overall/help-center.module.scss
  packages/components/src/components/Overall/help-center.tsx
  packages/components/src/components/Overall/list.module.scss
  packages/components/src/components/Overall/overview.module.scss
  packages/components/src/components/Overall/overview.tsx
  packages/components/src/components/Overall/project.module.scss
  packages/components/src/components/Overall/project.tsx
  packages/components/src/pages/BundleSize/components/card.module.scss
  packages/components/src/pages/BundleSize/components/cards.tsx
  packages/components/src/pages/Overall/index.module.scss
  packages/components/src/pages/Overall/index.tsx
  packages/components/src/pages/Overall/responsiveLayout.tsx
  packages/components/src/utils/i18n/cn.ts
  packages/components/src/utils/i18n/en.ts
  pnpm-lock.yaml
Labels: change: fix

#679 fix: the module api error in rspack 1.2.0-alpha
  packages/core/src/build-utils/build/module-graph/treeShaking.ts
  packages/core/src/build-utils/build/module-graph/webpack/transform.ts
  packages/core/src/build-utils/build/utils/plugin.ts
  packages/core/src/build-utils/common/module-graph/compatible.ts
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
Labels: change: fix

#683 perf: replace `serve-static` with `sirv`
  packages/client/package.json
  packages/client/rsbuild.config.ts
  packages/sdk/package.json
  packages/sdk/src/sdk/server/index.ts
  pnpm-lock.yaml
Labels: change: perf

#684 fix: remove legacy webpack 4 compatibility code
  e2e/cases/doctor-webpack/plugins/loader.test.ts
  packages/core/src/build-utils/build/module-graph/webpack/transform.ts
  packages/core/src/build-utils/build/utils/loader.ts
  packages/core/src/build-utils/common/webpack/compatible.ts
  packages/core/src/inner-plugins/plugins/loader.ts
  packages/core/src/inner-plugins/plugins/summary.ts
  packages/utils/src/common/summary.ts
Labels: change: fix

#685 fix: failed to call `getResolvedModule` in Rspack
  packages/core/src/build-utils/build/module-graph/webpack/transform.ts
Labels: change: fix

#686 fix: fix ui issues
  packages/client/package.json
  packages/components/package.json
  packages/components/src/common/svg/navbar/bundle-size-active.svg
  packages/components/src/common/svg/navbar/bundle-size-inactive.svg
  packages/components/src/common/svg/navbar/compile-analysis-active.svg
  packages/components/src/common/svg/navbar/compile-analysis-inactive.svg
  packages/components/src/common/svg/navbar/overall-active.svg
  packages/components/src/common/svg/navbar/overall-inactive.svg
  packages/components/src/common/svg/overall/bundle-size-icon.svg
  packages/components/src/common/svg/overall/compile-icon.svg
  packages/components/src/common/svg/overall/overall-icon.svg
  packages/components/src/components/Alert/ecma-version-check.module.scss
  packages/components/src/components/Alert/ecma-version-check.tsx
  packages/components/src/components/Alert/package-relation.tsx
  packages/components/src/components/Alerts/bundle-alert.module.scss
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/components/src/components/Alerts/collapse.tsx
  packages/components/src/components/Alerts/overlay.module.scss
  packages/components/src/components/Alerts/overlay.tsx
  packages/components/src/components/Card/index.tsx
  packages/components/src/components/Card/size.module.scss
  packages/components/src/components/Card/size.tsx
  packages/components/src/components/Charts/minify.tsx
  packages/components/src/components/Configuration/builder.tsx
  packages/components/src/components/Layout/menus.tsx
  packages/components/src/components/Overall/bundle.module.scss
  packages/components/src/components/Overall/bundle.tsx
  packages/components/src/components/Overall/card.module.scss
  packages/components/src/components/Overall/compile.tsx
  packages/components/src/components/Overall/help-center.module.scss
  packages/components/src/components/Overall/help-center.tsx
  packages/components/src/components/Overall/project.tsx
  packages/components/src/pages/BundleSize/components/cards.tsx
  packages/components/src/pages/Overall/index.module.scss
  packages/components/src/pages/Overall/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#671 feat(ui): optimize the bundle size page
  examples/modern-minimal/modern.config.ts
  examples/rsbuild-minimal/package.json
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/components/src/components/CodeViewer/viewer.tsx
  packages/components/src/components/FileTree/css.svg
  packages/components/src/components/FileTree/html.svg
  packages/components/src/components/FileTree/image.svg
  packages/components/src/components/FileTree/index.scss
  packages/components/src/components/FileTree/js.svg
  packages/components/src/components/FileTree/unkown-file.svg
  packages/components/src/components/Form/keyword.tsx
  packages/components/src/components/Keyword/index.tsx
  packages/components/src/components/Keyword/style.module.scss
  packages/components/src/components/Layout/bundle-size-icon.svg
  packages/components/src/components/Layout/compile-icon.svg
  packages/components/src/components/Layout/overall-icon.svg
  packages/components/src/components/Loader/Analysis/index.tsx
  packages/components/src/components/Loader/Analysis/input.svg
  packages/components/src/components/Loader/Analysis/output.svg
  packages/components/src/components/Loader/step.svg
  packages/components/src/components/TextDrawer/index.tsx
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/components/src/pages/BundleSize/components/index.module.scss
  packages/components/src/pages/BundleSize/components/index.tsx
  packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.scss
  packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.tsx
  packages/components/src/pages/ModuleAnalyze/fileTree.tsx
  packages/components/src/pages/ModuleAnalyze/index.scss
  packages/components/src/pages/ModuleAnalyze/index.tsx
  packages/components/src/pages/WebpackPlugins/index.tsx
  packages/components/src/utils/file.tsx
  packages/document/package.json
  pnpm-lock.yaml
Labels: change: feat

#688 fix(ui): fix some ui problems
  packages/components/src/components/Charts/utils.ts
  packages/components/src/components/Configuration/builder.tsx
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/executions.tsx
  packages/components/src/components/Opener/code.tsx
  packages/components/src/components/Select/index.scss
  packages/components/src/components/Select/index.tsx
  packages/components/src/pages/BundleSize/components/index.module.scss
  packages/components/src/pages/WebpackPlugins/index.scss
  packages/components/src/pages/WebpackPlugins/index.tsx
Labels: change: fix

#690 fix(UI): Overall & Bunlde page ui problem
  packages/components/src/components/Layout/menus.tsx
  packages/components/src/components/Layout/progress.tsx
  packages/components/src/pages/BundleSize/components/index.module.scss
  packages/components/src/pages/BundleSize/components/index.tsx
  packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.scss
  packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.tsx
  packages/components/src/pages/ModuleAnalyze/index.scss
  packages/components/src/pages/ModuleAnalyze/index.tsx
  packages/components/src/pages/Overall/index.tsx
  packages/components/src/pages/WebpackPlugins/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#693 feat(ui): update website logo
  packages/components/src/components/Layout/header.tsx
Labels: change: feat

#696 fix: broken `pnpm-lock.yaml`
  pnpm-lock.yaml
Labels: change: fix

#699 fix(ui): the overall ui problem
  packages/components/src/components/Alerts/collapse.tsx
  packages/components/src/components/Card/size.module.scss
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/pages/BundleSize/components/cards.tsx
Labels: change: fix

#703 docs: add preview video to README.md
  README.md
Labels: change: docs

#704 docs: add preview video to README.zh-CN.md
  README.zh-CN.md
Labels: change: docs

#705 fix(deps): replace deprecated acorn-import-assertions
  packages/utils/package.json
  packages/utils/src/rule-utils/parser/parser.ts
  pnpm-lock.yaml
Labels: change: fix

#708 fix(UI): overall cards font overflow problem
  packages/components/src/components/Overall/bundle.module.scss
Labels: change: fix

#711 feat: logo as home link
  packages/components/src/components/Layout/header.scss
  packages/components/src/components/Layout/header.tsx
  packages/types/src/client.ts
Labels: change: feat

#726 fix: failed to call `module.getExportsType` method
  packages/core/src/build-utils/build/module-graph/webpack/transform.ts
  packages/core/src/build-utils/common/webpack/compatible.ts
Labels: change: fix

#727 fix(UI): invalid font family for loader analysis text
  packages/components/src/components/Loader/Analysis/style.module.scss
Labels: change: fix

#738 docs: update "getting started" guide section for Rsbuild
  packages/document/docs/en/guide/start/quick-start-shared.mdx
  packages/document/docs/zh/guide/start/quick-start-shared.mdx
Labels: change: docs
