Repository web-infra-dev/rsdoctor, pull requests merged in 2025-06, with the labels that each got.

#1105 fix: add info for banner plugin when drop_console is true
  e2e/cases/doctor-rspack/banner-plugin.test.ts
  e2e/package.json
  packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
  pnpm-lock.yaml
Labels: change: fix

#1118 feat: add tooltips for bundle size tags
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/document/docs/en/guide/usage/bundle-size.mdx
  packages/document/docs/zh/guide/usage/bundle-size.mdx
Labels: change: feat

#1117 feat: support bailout_reason
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/components/src/pages/ModuleAnalyze/fileTree.tsx
  packages/components/src/pages/ModuleAnalyze/index.tsx
  packages/core/src/build-utils/common/module-graph/transform.ts
  packages/core/tests/common/module-graph/__snapshots__/transform.test.ts.snap
  packages/graph/src/graph/module-graph/module.ts
  packages/types/src/plugin/baseStats.ts
  packages/types/src/sdk/module.ts
Labels: change: feat

#1058 fix: sdk types
  packages/sdk/tests/utils.ts
Labels: change: fix

#1139 docs: tile graph documentation
  packages/document/docs/en/guide/usage/bundle-size.mdx
  packages/document/docs/zh/guide/usage/bundle-size.mdx
Labels: change: docs
