Repository web-infra-dev/rsdoctor, pull requests merged in 2025-04, with the labels that each got.

#892 feat: ai support qwen
  packages/ai/package.json
  packages/ai/src/mcp/index.ts
  packages/ai/src/mcp/server.ts
  packages/ai/src/model/index.ts
  pnpm-lock.yaml
Labels: change: feat

#894 fix: delete some unuse options
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/types/plugin.ts
  packages/rspack-plugin/src/multiple.ts
  packages/rspack-plugin/src/plugin.ts
  packages/types/src/sdk/instance.ts
  packages/webpack-plugin/src/multiple.ts
  packages/webpack-plugin/src/plugin.ts
Labels: change: fix

#913 fix: Cleans up diff editor on unmount
  packages/components/src/components/CodeViewer/diff.tsx
Labels: change: fix

#912 feat: UI execution diff view add side-by-side check
  packages/components/src/components/Loader/executions.tsx
Labels: change: feat

#922 feat: add the logic of registering resources
  packages/ai/src/mcp/resource.ts
  packages/ai/src/mcp/server.ts
  packages/ai/src/mcp/socket.ts
  packages/ai/src/mcp/tools.ts
  packages/ai/src/prompt/index.ts
  packages/ai/src/resources/rsdoctor-config.md
  packages/ai/src/resources/rsdoctor-context.md
Labels: change: feat

#938 feat(ui): optimize treeNode style
  packages/components/src/components/FileTree/index.scss
  packages/components/src/pages/BundleSize/components/index.module.scss
  packages/components/src/pages/Overall/index.module.scss
Labels: change: feat

#923 feat: analysis filetree UI
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/Analysis/index.tsx
  packages/components/src/components/Loader/Analysis/style.module.scss
Labels: change: feat

#969 feat: module instance add issuerPath
  packages/core/src/build-utils/common/module-graph/transform.ts
  packages/core/tests/common/module-graph/__snapshots__/transform.test.ts.snap
  packages/graph/src/graph/module-graph/module.ts
  packages/types/src/plugin/baseStats.ts
  packages/types/src/sdk/module.ts
Labels: change: feat

#965 feat: support mcp-server-rsdoctor
  .gitignore
  biome.json
  packages/ai/.env.sample
  packages/ai/.gitignore
  packages/ai/README.md
  packages/ai/package.json
  packages/ai/rslib.config.ts
  packages/ai/src/index.ts
  packages/ai/src/mcp/client.ts
  packages/ai/src/mcp/index.ts
  packages/ai/src/mcp/prompt.ts
  packages/ai/src/mcp/resource.ts
  packages/ai/src/mcp/server.ts
  packages/ai/src/mcp/socket.ts
  packages/ai/src/mcp/tools.ts
  packages/ai/src/model/coze.ts
  packages/ai/src/model/index.ts
  packages/ai/src/model/openai.ts
  packages/ai/src/prompt/assets.ts
  packages/ai/src/prompt/code.ts
  packages/ai/src/prompt/deps.ts
  packages/ai/src/prompt/functions.ts
  packages/ai/src/prompt/index.ts
  packages/ai/src/prompt/schema.ts
  packages/ai/src/resources/rsdoctor-config.md
  packages/ai/src/resources/rsdoctor-context.md
  packages/ai/src/schema.ts
  packages/ai/src/types/index.d.ts
  packages/ai/src/utils/chunks.ts
  packages/ai/src/utils/env.ts
  packages/ai/src/utils/index.ts
  packages/ai/tests/chunks.test.ts
  packages/ai/tests/code.test.ts
  packages/ai/tests/fixtures/chunks.cjs
  packages/ai/tests/fixtures/chunks_client.json
  packages/ai/tests/fixtures/deps.json
  packages/ai/tests/fixtures/filtered_modules.json
  packages/ai/tests/fixtures/group.json
  packages/ai/tests/fixtures/modules_client.json
  packages/ai/tests/fixtures/result.json
  packages/ai/tests/fixtures/test.cjs
  packages/ai/tests/index.test.ts
  packages/ai/tests/socket.test.ts
  packages/ai/tests/tsconfig.json
  packages/ai/tests/utils.test.ts
  packages/ai/tsconfig.build.json
  packages/ai/tsconfig.json
  packages/ai/vitest.config.ts
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/types/src/sdk/module.ts
  packages/types/src/sdk/server/apis/index.ts
  packages/utils/src/common/data/index.ts
  packages/utils/src/logger.ts
  pnpm-lock.yaml
Labels: change: feat

#994 docs: optimize the docs for using rsdoctor in the Next.js + Rspack
  packages/document/docs/en/guide/start/quick-start-shared.mdx
  packages/document/docs/zh/guide/start/quick-start-shared.mdx
Labels: change: docs

#1021 feat: rsdoctor mcp server
  .gitignore
  e2e/package.json
  examples/modern-minimal/package.json
  examples/multiple-minimal/package.json
  examples/rspress-minimal/package.json
  examples/webpack-minimal/package.json
  package.json
  packages/ai/README.md
  packages/ai/bin/rsdoctor-mcp
  packages/ai/package.json
  packages/ai/rslib.config.ts
  packages/ai/src/index.ts
  packages/ai/src/mcp/client.ts
  packages/ai/src/mcp/index.ts
  packages/ai/src/model/index.ts
  packages/ai/src/server/index.ts
  packages/ai/src/server/prompt.ts
  packages/ai/src/server/resource.ts
  packages/ai/src/server/server.ts
  packages/ai/src/server/socket.ts
  packages/ai/src/server/tools.ts
  packages/ai/tests/fixtures/result.json
  packages/client/package.json
  packages/components/package.json
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/core/package.json
  packages/core/src/build-utils/common/module-graph/transform.ts
  packages/document/package.json
  packages/graph/package.json
  packages/graph/src/graph/module-graph/module.ts
  packages/rspack-plugin/package.json
  packages/sdk/package.json
  packages/types/package.json
  packages/types/src/plugin/baseStats.ts
  packages/types/src/sdk/module.ts
  packages/types/src/sdk/server/apis/index.ts
  packages/utils/package.json
  packages/utils/src/common/data/index.ts
  packages/webpack-plugin/package.json
  pnpm-lock.yaml
  scripts/test-helper/package.json
Labels: change: feat

#1026 fix(@scripts/test-helper): fix type path error
  scripts/test-helper/package.json
Labels: change: fix

#1037 docs: fix links in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: change: docs

#1041 fix: add spacing to bundled and source sizes
  packages/components/src/pages/BundleSize/components/asset.tsx
Labels: change: fix

#1039 fix: improve clarity of rule `E1001`
  packages/types/src/rule/code/E1001.ts
Labels: change: fix

#1038 docs: update license badge link
  README.md
Labels: change: docs

#1040 fix: improve `OverlayAlerts` spacing and add pluralization
  packages/components/src/components/Alerts/overlay.tsx
Labels: change: fix

#1028 feat(components): refactor CodeViewer and DiffViewer
  packages/components/package.json
  packages/components/src/components/CodeViewer/config.ts
  packages/components/src/components/CodeViewer/diff.tsx
  packages/components/src/components/CodeViewer/highlight.tsx
  packages/components/src/components/CodeViewer/viewer.tsx
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/components/src/components/Loader/executions.tsx
  packages/components/src/components/Resolver/analysis.tsx
  packages/components/src/components/base/CodeViewer/index.module.scss
  packages/components/src/components/base/CodeViewer/index.tsx
  packages/components/src/components/base/CodeViewer/interface.ts
  packages/components/src/components/base/CodeViewer/useCodeDrawer.tsx
  packages/components/src/components/base/CodeViewer/utils.ts
  packages/components/src/components/base/DiffViewer/index.module.scss
  packages/components/src/components/base/DiffViewer/index.tsx
  packages/components/src/components/base/DiffViewer/interface.ts
  packages/components/src/components/base/DiffViewer/useDiffDrawer.tsx
  packages/components/src/components/base/DiffViewer/utils.ts
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/components/src/pages/BundleSize/components/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#1042 feat: support rsdoctor-mcp-server
  .changeset/config.json
  .gitignore
  biome.json
  packages/ai/.env.sample
  packages/ai/.gitignore
  packages/ai/README.md
  packages/ai/bin/rsdoctor-mcp
  packages/ai/package.json
  packages/ai/rslib.config.ts
  packages/ai/src/index.ts
  packages/ai/src/prompt/assets.ts
  packages/ai/src/prompt/bundle.ts
  packages/ai/src/prompt/code.ts
  packages/ai/src/prompt/deps.ts
  packages/ai/src/prompt/functions.ts
  packages/ai/src/prompt/index.ts
  packages/ai/src/prompt/schema.ts
  packages/ai/src/resources/rsdoctor-config.md
  packages/ai/src/resources/rsdoctor-context.md
  packages/ai/src/schema.ts
  packages/ai/src/server/index.ts
  packages/ai/src/server/prompt.ts
  packages/ai/src/server/resource.ts
  packages/ai/src/server/server.ts
  packages/ai/src/server/socket.ts
  packages/ai/src/server/tools.ts
  packages/ai/src/types/index.d.ts
  packages/ai/src/utils/chunks.ts
  packages/ai/src/utils/env.ts
  packages/ai/src/utils/index.ts
  packages/ai/tests/chunks.test.ts
  packages/ai/tests/code.test.ts
  packages/ai/tests/fixtures/chunks_client.json
  packages/ai/tests/fixtures/deps.json
  packages/ai/tests/fixtures/group.json
  packages/ai/tests/fixtures/result.json
  packages/ai/tests/fixtures/test.cjs
  packages/ai/tests/index.test.ts
  packages/ai/tests/model/coze.ts
  packages/ai/tests/model/index.ts
  packages/ai/tests/model/openai.ts
  packages/ai/tests/socket.test.ts
  packages/ai/tests/tsconfig.json
  packages/ai/tests/utils.test.ts
  packages/ai/tsconfig.build.json
  packages/ai/tsconfig.json
  packages/ai/vitest.config.ts
  packages/client/rsbuild.config.ts
  packages/types/src/sdk/server/apis/index.ts
  packages/types/src/sdk/server/apis/loader.ts
  packages/utils/src/common/data/index.ts
  packages/utils/src/common/loader.ts
  packages/utils/src/logger.ts
  pnpm-lock.yaml
  vitest.workspace.ts
Labels: change: feat

#1051 fix: remove tsconfig.json from the test directory and update the path
  packages/sdk/tests/server/apis/project.test.ts
  packages/sdk/tests/tsconfig.json
Labels: change: fix

#1044 feat(components): Change old code to new CodeViewer and DiffViewer and clear unused code
  packages/components/src/components/Alert/change.tsx
  packages/components/src/components/Alert/index.scss
  packages/components/src/components/Alert/view.tsx
  packages/components/src/components/BundleDiff/DiffContainer/assets.tsx
  packages/components/src/components/BundleDiff/DiffContainer/cards.tsx
  packages/components/src/components/BundleDiff/DiffContainer/changes.tsx
  packages/components/src/components/BundleDiff/DiffContainer/constants.ts
  packages/components/src/components/BundleDiff/DiffContainer/diff.tsx
  packages/components/src/components/BundleDiff/DiffContainer/index.tsx
  packages/components/src/components/BundleDiff/DiffContainer/modules.tsx
  packages/components/src/components/BundleDiff/DiffContainer/overview.tsx
  packages/components/src/components/BundleDiff/DiffContainer/packages.tsx
  packages/components/src/components/BundleDiff/DiffContainer/row.tsx
  packages/components/src/components/BundleDiff/DiffContainer/types.ts
  packages/components/src/components/BundleDiff/DiffContainer/utils.tsx
  packages/components/src/components/BundleDiff/DiffServerAPIProvider/index.tsx
  packages/components/src/components/BundleDiff/constants.tsx
  packages/components/src/components/BundleDiff/index.ts
  packages/components/src/components/CodeViewer/config.ts
  packages/components/src/components/CodeViewer/diff.tsx
  packages/components/src/components/CodeViewer/highlight.tsx
  packages/components/src/components/CodeViewer/index.tsx
  packages/components/src/components/CodeViewer/viewer.tsx
  packages/components/src/components/Loader/executions.tsx
  packages/components/src/components/Resolver/analysis.tsx
  packages/components/src/components/base/CodeViewer/index.tsx
  packages/components/src/components/base/CodeViewer/utils.ts
  packages/components/src/components/base/DiffViewer/index.tsx
  packages/components/src/components/base/index.ts
  packages/components/src/components/index.ts
  packages/components/src/pages/BundleSize/components/asset.tsx
  packages/components/src/pages/BundleSize/components/editor.tsx
  packages/components/src/pages/Resources/BundleDiff/DiffContainer/changes.tsx
  packages/components/src/pages/TreeShaking/editor.tsx
  packages/components/src/pages/TreeShaking/utils.tsx
  packages/components/src/utils/index.ts
  packages/components/src/utils/monaco.ts
Labels: change: feat

#1063 docs(llms): bump rspress to 2.0.0-beta.3 and ship llms.txt
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: docs
