Repository web-infra-dev/rsdoctor, pull requests merged in 2025-05, with the labels that each got.

#1072 feat: rsdoctor mcp get auto port
  examples/rsbuild-minimal/rsbuild.config.ts
  packages/ai/src/server/server.ts
  packages/ai/src/server/socket.ts
  packages/ai/src/server/tools.ts
  packages/sdk/src/sdk/server/index.ts
  packages/utils/src/common/data/index.ts
  packages/utils/src/common/global-config.ts
  packages/utils/src/common/index.ts
Labels: change: feat

#1076 fix(server): avoid using browser-restricted port numbers
  packages/utils/src/build/server.ts
Labels: change: fix

#1077 fix(rspack-plugin): mark @rspack/core as optional peer
  packages/rspack-plugin/package.json
  packages/rspack-plugin/src/multiple.ts
Labels: change: fix

#1085 fix: the rsdoctor mcp-server change the builder property to compiler
  packages/ai/src/server/socket.ts
Labels: change: fix

#1088 docs: optimize the documentation of the rsdoctor-mcp-server
  packages/ai/README.md
  packages/ai/README.zh-CN.md
Labels: change: docs

#1092 docs: add Rstest to homepage
  packages/document/i18n.json
  packages/document/package.json
  packages/document/theme/components/ToolStack.tsx
  pnpm-lock.yaml
Labels: change: docs

#1097 docs: update Rstack introduction
  README.md
  README.zh-CN.md
  packages/document/docs/en/guide/start/intro.mdx
  packages/document/docs/zh/guide/start/intro.mdx
  packages/document/package.json
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: docs

#1099 docs(rspress): use @rspress/plugin-algolia for search and upgrade rspress version 2.0.0-beta.6
  packages/document/docs/en/guide/start/cli.mdx
  packages/document/docs/zh/guide/start/cli.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/document/theme/index.tsx
  pnpm-lock.yaml
Labels: change: docs

#1102 fix: remove unexpected test code when NODE_ENV is test
  packages/core/src/build-utils/build/module-graph/webpack/transform.ts
Labels: change: fix
