Repository web-infra-dev/rsdoctor, pull requests merged in 2025-08, with the labels that each got.

#1217 feat: fix typo and improve alert collapse sorting
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/components/src/components/Alerts/collapse.tsx
Labels: change: feat

#1231 docs: add quick install buttons for mcp
  packages/ai/README.md
  packages/ai/README.zh-CN.md
  packages/document/docs/en/guide/start/mcp.mdx
  packages/document/docs/zh/guide/start/mcp.mdx
  packages/document/rspress.config.ts
Labels: change: docs

#1247 feat: add stats-json analysis with @rsdoctor/cli
  packages/cli/package.json
  packages/cli/src/commands/analyze.ts
  packages/cli/src/commands/stats-analyze.ts
  packages/cli/src/constants.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: change: feat

#1235 docs: version 1.2.0 blog
  packages/document/docs/en/_meta.json
  packages/document/docs/en/blog/release/_meta.json
  packages/document/docs/en/blog/release/release-note-1_2.mdx
  packages/document/docs/en/guide/usage/bundle-size.mdx
  packages/document/docs/zh/_meta.json
  packages/document/docs/zh/blog/release/_meta.json
  packages/document/docs/zh/blog/release/release-note-1_2.mdx
  packages/document/docs/zh/guide/usage/bundle-size.mdx
Labels: change: docs

#1260 fix(types): relieve original import path
  packages/types/src/sdk/module.ts
  packages/types/src/sdk/server/apis/index.ts
Labels: change: fix

#1267 fix: devtool module file template
  packages/core/src/inner-plugins/plugins/bundle.ts
Labels: change: fix

#1272 perf: optimize the stats.toJson's time-consuming
  packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
  packages/types/src/plugin/baseStats.ts
Labels: change: perf

#1271 fix: proxy loader return undefined error
  package.json
  packages/core/src/inner-plugins/loaders/proxy.ts
  packages/core/src/inner-plugins/plugins/loader.ts
Labels: change: fix

#1278 fix: ensure unique collapsible key
  packages/components/src/components/Alerts/collapse-cross-chunks.tsx
  packages/components/src/components/Alerts/collapse.tsx
Labels: change: fix

#1270 feat: the config options changes
  packages/cli/src/commands/analyze.ts
  packages/core/package.json
  packages/core/src/inner-plugins/utils/config.ts
  packages/core/src/inner-plugins/utils/index.ts
  packages/core/src/inner-plugins/utils/normalize-config.ts
  packages/core/src/types/plugin.ts
  packages/core/tests/build/utils/config.test.ts
  packages/rspack-plugin/src/multiple.ts
  packages/rspack-plugin/src/plugin.ts
  packages/sdk/src/sdk/sdk/core.ts
  packages/types/src/sdk/instance.ts
  packages/webpack-plugin/src/multiple.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/tests/multiple.test.ts
Labels: change: feat

#1279 docs: fix rslib link
  README.md
  README.zh-CN.md
  packages/document/docs/en/blog/release/release-note-1_0.mdx
  packages/document/docs/en/guide/start/intro.mdx
  packages/document/docs/zh/blog/release/release-note-1_0.mdx
  packages/document/docs/zh/guide/start/intro.mdx
Labels: change: docs
