Repository web-infra-dev/rsdoctor, pull requests merged in 2025-02, with the labels that each got.

#741 fix(rspack-plugin): correct the dist types directory
  packages/rspack-plugin/tsconfig.json
Labels: change: fix

#737 fix: switch to sirv and disable cache
  packages/client/package.json
  packages/client/rsbuild.config.ts
  packages/sdk/package.json
  packages/sdk/src/sdk/server/index.ts
  pnpm-lock.yaml
Labels: change: fix

#749 fix: expriments.backCompat problem
  e2e/cases/doctor-webpack/experiments.test.ts
  e2e/package.json
  packages/core/src/build-utils/build/utils/plugin.ts
  packages/core/src/inner-plugins/utils/plugin.ts
Labels: change: fix

#755 fix(sdk): the error of websocket
  packages/components/src/utils/socket.ts
Labels: change: fix

#757 docs: use Rstack unified homepage
  packages/document/docs/en/index.md
  packages/document/docs/zh/index.md
  packages/document/i18n.json
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/document/theme/components/Copyright.module.scss
  packages/document/theme/components/Copyright.tsx
  packages/document/theme/components/Features.module.scss
  packages/document/theme/components/Features.tsx
  packages/document/theme/components/Hero.module.scss
  packages/document/theme/components/Hero.tsx
  packages/document/theme/components/ToolStack.module.scss
  packages/document/theme/components/ToolStack.tsx
  packages/document/theme/components/utils.ts
  packages/document/theme/index.css
  packages/document/theme/index.tsx
  packages/document/theme/pages/index.tsx
  pnpm-lock.yaml
Labels: change: docs

#756 fix: summary loader consuming time of dirs
  packages/components/src/components/Loader/Analysis/files.tsx
  packages/utils/src/common/loader.ts
Labels: change: fix

#758 feat: support cross chunks package rule
  examples/modern-minimal/modern.config.ts
  examples/modern-minimal/package.json
  examples/modern-minimal/src/myapp/routes/index.css
  examples/modern-minimal/src/myapp/routes/layout.tsx
  examples/modern-minimal/src/myapp/routes/page.tsx
  examples/modern-minimal/src/myapp2/routes/index.css
  examples/modern-minimal/src/myapp2/routes/layout.tsx
  examples/modern-minimal/src/myapp2/routes/page.tsx
  examples/modern-minimal/src/utils/utils.ts
  packages/components/src/components/Alerts/bundle-alert.tsx
  packages/components/src/components/Alerts/collapse-cross-chunks.tsx
  packages/components/src/pages/Overall/index.tsx
  packages/core/src/rules/rules/cross-chunks-package/index.ts
  packages/core/src/rules/rules/cross-chunks-package/types.ts
  packages/core/src/rules/rules/cross-chunks-package/utils.ts
  packages/core/src/rules/rules/default-import-check/index.ts
  packages/core/src/rules/rules/index.ts
  packages/document/docs/en/guide/usage/compile-alerts.mdx
  packages/document/docs/en/guide/usage/rule-config.mdx
  packages/document/docs/zh/guide/usage/compile-alerts.mdx
  packages/document/docs/zh/guide/usage/rule-config.mdx
  packages/graph/src/graph/package-graph/graph.ts
  packages/graph/src/graph/package-graph/package.ts
  packages/graph/tests/__snapshots__/module-graph.test.ts.snap
  packages/sdk/tests/__snapshots__/module-graph.test.ts.snap
  packages/types/src/rule/code/E1002.ts
  packages/types/src/rule/code/E1005.ts
  packages/types/src/rule/code/index.ts
  packages/types/src/rule/data.ts
  packages/types/src/sdk/package.ts
  pnpm-lock.yaml
Labels: change: feat

#763 feat: support search module in all chunks
  packages/components/src/pages/BundleSize/components/index.module.scss
  packages/components/src/pages/BundleSize/components/index.tsx
  packages/components/src/pages/BundleSize/components/search-modal.tsx
  packages/types/src/sdk/server/apis/graph.ts
  packages/types/src/sdk/server/apis/index.ts
  packages/utils/src/common/data/index.ts
Labels: change: feat

#766 fix: loader page ui problem
  packages/utils/src/common/loader.ts
Labels: change: fix

#770 fix(ui): overall's bundle alerts
  packages/components/src/components/Alerts/bundle-alert.tsx
Labels: change: fix

#775 docs: add rules documents
  packages/document/docs/en/blog/release/release-note-0_3.mdx
  packages/document/docs/en/guide/_meta.json
  packages/document/docs/en/guide/custom/_meta.json
  packages/document/docs/en/guide/more/faq.mdx
  packages/document/docs/en/guide/rules/_meta.json
  packages/document/docs/en/guide/rules/rule-custom.mdx
  packages/document/docs/en/guide/rules/rules.mdx
  packages/document/docs/en/guide/rules/upload-data.mdx
  packages/document/docs/en/guide/usage/bundle-alerts.mdx
  packages/document/docs/en/guide/usage/compile-alerts.mdx
  packages/document/docs/en/guide/usage/rule-config.mdx
  packages/document/docs/public/bundle-alerts.png
  packages/document/docs/public/cross-chunks-package.png
  packages/document/docs/zh/blog/release/release-note-0_3.mdx
  packages/document/docs/zh/guide/_meta.json
  packages/document/docs/zh/guide/custom/_meta.json
  packages/document/docs/zh/guide/more/faq.mdx
  packages/document/docs/zh/guide/rules/_meta.json
  packages/document/docs/zh/guide/rules/rule-custom.mdx
  packages/document/docs/zh/guide/rules/rules.mdx
  packages/document/docs/zh/guide/rules/upload-data.mdx
  packages/document/docs/zh/guide/usage/bundle-alerts.mdx
  packages/document/docs/zh/guide/usage/compile-alerts.mdx
  packages/document/docs/zh/guide/usage/resolver.mdx
  packages/document/docs/zh/guide/usage/rule-config.mdx
Labels: change: docs

#777 docs: change options document
  packages/document/docs/en/config/options/options.mdx
  packages/document/docs/zh/config/options/options.mdx
Labels: change: docs

#779 fix: the problem of loader-performance-optimization rule
  packages/components/src/components/Alerts/bundle.tsx
  packages/components/src/components/Alerts/list.tsx
  packages/core/src/rules/rules/loader-performance-optimization/index.ts
  packages/core/src/rules/rules/loader-performance-optimization/types.ts
Labels: change: fix

#782 docs: add experiments enableNativePlugin option
  packages/document/docs/en/config/options/options.mdx
  packages/document/docs/zh/config/options/options.mdx
Labels: change: docs
